#use_frameworks!

platform :ios, '8.0'

target 'XJPCategoryKit_Example' do
  pod 'XJPCategoryKit', :path => '../'

  target 'XJPCategoryKit_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'YYModel'
  end
end
